### ISSUE TITLE
Could Not Expand Globs - Context Cancelled

### ISSUE THREAD

**Issue by gkramer** [lomik/go-carbon#479]
Error in Log:
[2022-07-18T20:59:06.441Z] ERROR [access] fetch failed {"handler": "render", "url": "/render/?format=protobuf&from=1658156341&target=MyTarget%24JmxTimer.update_session_exception_none.999thPercentile&until=1658177941", "peer": "10.128.27.189:50684", "carbonapi_uuid": "e5737414-2d9a-4d85-b89c-a253b13380dc", "format": "carbonapi_v2_pb", "targets": ["MyTarget$JmxTimer.update_session_exception_none.999thPercentile"], "runtime_seconds": 0.000098906, "reason": "failed to read data", "http_code": 400, "error": "could not expand globs - context canceled"}

I'm also seeing 'find failed' with the following reasons:
"reason": "Internal error while processing request", "error": "could not expand globs - context canceled", "http_code": 500
"reason": "Internal error while processing request", "http_code": 500

It should be noted that some of these queries are trying to merge 80+ graphs at runtime, which may be contributing to the issue.

Please also note that we've turned off indexing, as we have >30TB of whisper data which results in enormous amounts of RAM utilisation.

Any assistance in resolving these issues would be really appreciated!

**Comment by gkramer** [comment]
@bom-d-van Any chance you should shed some light on this? :)

**Comment by bom-d-van** [comment]
it's most likely hitting a timeout. how many whisper files do you have for the server? are you able to `ls` the whisper file?

**Comment by gkramer** [comment]
@bom-d-van Its not exhausting IOps, CPU or RAM. There are 30+ TB of whisper files, so a lot! Any suggestions for improving performance?

**Comment by Civil** [comment]
@gkramer problem with no index at all approach is that you rely on OS to be able to give you list of files fast.

However, depending on your filesystem and other factors `stat` syscall on folder that have a lot of entries might take time.

That is also the reason why @bom-d-van asked to try to measure how fast `ls` works in same whisper tree. If it's also slow, then there is not much you can do about performance (you can try to split your whisper tree into multiple sub-trees for example, but that way you'll add more problems to solve, like load balancing for ingestion on top of multiple go-carbon's)

**Comment by gkramer** [comment]
@Civil Thank you for the response. So the most efficient approach is to add more RAM [in order to enable indexing] to the system? (I find myself wondering about the impact of using swap, if only to validate the indexing approach temporarily - this is the primary service running on the box)

side points:
* Are there any timeouts that can be bumped up to reduce the likelihood of errors caused in this regard? [I've pushed up all the relevant timeouts I could find in the config, all with little/no benefit]
* surely the logic could be improved to only run syscall on the relevant child directories/namespaces, thereby reducing the importance of the index?
* We're currently using (AWS) EBS storage with gp3, and I've considered using io2, but I doubt it will improve performance sufficiently to resolve the problem above: Seems like increased RAM is the best approach, albeit an expensive one... [me: ponders using swap a little more]
* How efficient is the in memory indexing? If I were to swap to disk, would I still see a net benefit in response times?

**Comment by gkramer** [comment]
@Civil @bom-d-van The problem is back, and indexing is turned on - both! Any ideas? Should I look to upgrade the disks to host-based SSD? It wouldnt appear as if this is the bottleneck, as IOps never spike above 4k, and the allocation is 8k. I'm also seeing upstream issues with carbonapi, but I'd prefer to resolve the go-carbon issues first.

Do you know if the developers have stress-tested the daemon for parallel queries - as in aggregating 50+ wsp files? I'd really like to get this issue resolved and behind me :)

Thanks for all your advice and insight to date!

**Comment by bom-d-van** [comment]
> The problem is back, and indexing is turned on - both! Any ideas? 

hi, can you share the config for go-carbon for us to have more context?

> Do you know if the developers have stress-tested the daemon for parallel queries - as in aggregating 50+ wsp files? I'd really like to get this issue resolved and behind me :)

50+ metrics should not be a problem in my experience. but usually the servers that I have seen running go-carbon has 96-128GB of memories and 16+ cpu cores. so it feels like that you might have to either scale out and scale up.

What are the timeouts below that you have for carbonserver?

```
[carbonserver]
# Read and Write timeouts for HTTP server
read-timeout = "60s"
write-timeout = "60s"
# Request timeout for each API call
request-timeout = "60s"

# request-timeout would override the global request-timeout.
#
# [[carbonserver.api-per-path-rate-limiters]]
# path = "/metrics/render/"
# max-inflight-requests = 1
# request-timeout = "60s"
```

**Comment by gkramer** [comment]
@bom-d-van 

go-carbon.conf
```
[common]
user = "graphite"
graph-prefix = "carbon.agents.{host}"
metric-endpoint = "local"
metric-interval = "1m0s"
max-cpu = 8

[whisper]
data-dir = "/data/graphite/storage/whisper"
schemas-file = "/data/graphite/conf/storage-schemas.conf"
aggregation-file = "/data/graphite/conf/storage-aggregation.conf"
workers = 8
max-updates-per-second = 0
max-creates-per-second = 0
hard-max-creates-per-second = false
sparse-create = false
flock = true
enabled = true
hash-filenames = true
compressed = false
remove-empty-file = false

[cache]
max-size = 1000000    # 1000000
write-strategy = "max"

[udp]
listen = ":2503"
enabled = true
buffer-size = 0

[tcp]
listen = ":2503"
enabled = true
buffer-size = 0

[pickle]
listen = ":2504"
max-message-size = 67108864
enabled = true
buffer-size = 0

[carbonlink]
listen = "127.0.0.1:7502"
enabled = true
read-timeout = "30s"

[grpc]
listen = "127.0.0.1:7503"
enabled = true

[tags]
enabled = false
tagdb-url = "http://127.0.0.1:8000"
tagdb-chunk-size = 32
tagdb-update-interval = 100
local-dir = "/var/lib/graphite/tagging/"
tagdb-timeout = "1s"

[carbonserver]
listen = "0.0.0.0:8080"
enabled = true
buckets = 10
metrics-as-counters = false
read-timeout = "120s"
write-timeout = "60s"
query-cache-enabled = true
query-cache-size-mb = 0  # FIXME: Was: 0 / 1000
find-cache-enabled = true
trigram-index = true # FIXME: true
scan-frequency = "5m0s"
trie-index = true # FIXME: false
file-list-cache = ""
concurrent-index = false
realtime-index = 0
max-inflight-requests = 0
no-service-when-index-is-not-ready = false
cache-scan = false
max-globs = 100
fail-on-max-globs = false
max-metrics-globbed  = 1000000 # 20000
max-metrics-rendered = 500000
graphite-web-10-strict-mode = true
empty-result-ok = true
internal-stats-dir = ""
stats-percentiles = [99, 98, 95, 75, 50]

[dump]
enabled = false
path = "/var/lib/graphite/dump/"
restore-per-second = 0

[pprof]
listen = "localhost:7007"
enabled = false

[[logging]]
logger = ""
file = "/var/log/go-carbon/go-carbon.log"
level = "debug"
encoding = "mixed"
encoding-time = "iso8601"
encoding-duration = "seconds"
```

carbonapi.conf
```
listeners:
        - address: "0.0.0.0:8081"
listen: ":8081"

prefix: ""
useCachingDNSResolver: false
cachingDNSRefreshTime: "1m"
expvar:
  enabled: true
  pprofEnabled: false
  listen: ""
headersToPass:
  - "X-Dashboard-Id"
  - "X-Grafana-Org-Id"
  - "X-Panel-Id"
headersToLog:
  - "X-Dashboard-Id"
  - "X-Grafana-Org-Id"
  - "X-Panel-Id"
define:
  -
    name: "perMinute"
    template: "perSecond({{.argString}})|scale(60)"
notFoundStatusCode: 200
concurency: 1000
cache:
   # Type of caching. Valid: "mem", "memcache", "null"
   type: "mem"
   # Cache limit in megabytes
   size_mb: 0
   # Default cache timeout value. Identical to DEFAULT_CACHE_DURATION in graphite-web.
   defaultTimeoutSec: 60
   # Only used by memcache type of cache. List of memcache servers.
   memcachedServers:
       - "127.0.0.1:1234"
       - "127.0.0.2:1235"
cpus: 0
tz: ""

functionsConfig:
    graphiteWeb: /etc/go-carbon/graphTemplates.yaml
    timeShift: /etc/go-carbon/timeShift.yaml

maxBatchSize: 100
graphite:
    # Host:port where to send internal metrics
    # Empty = disabled
    host: "127.0.0.1:2123"
    interval: "60s"
    prefix: "carbon.api"
    # rules on how to construct metric name. For now only {prefix} and {fqdn} is supported.
    # {prefix} will be replaced with the content of {prefix}
    # {fqdn} will be repalced with fqdn
    pattern: "{prefix}.{fqdn}"
idleConnections: 10
pidFile: ""
upstreams:
    # Use TLD Cache. Useful when you have multiple backends that could contain
    # different TLDs.
    #
    # For example whenever you have multiple top level metric namespaces, like:
    #   one_min.some.metric
    #   ten_min.some_metric
    #   one_hour.some_metric
    #
    # `one_min`, `ten_min` and `one_hour` are considered to be TLDs
    # carbonapi by default will probe all backends and cache the responses
    # and will know which backends would contain the prefix of the request
    #
    # This option allows to disable that, which could be helpful for backends like
    # `clickhouse` or other backends where all metrics are part of the same cluster
    tldCacheDisabled: false

    # Number of 100ms buckets to track request distribution in. Used to build
    # 'carbon.zipper.hostname.requests_in_0ms_to_100ms' metric and friends.
    # Requests beyond the last bucket are logged as slow (default of 10 implies
    # "slow" is >1 second).
    # The last bucket is _not_ called 'requests_in_Xms_to_inf' on purpose, so
    # we can change our minds about how many buckets we want to have and have
    # their names remain consistent.
    buckets: 10

    # If request took more than specified amount of time, it will be logged as a slow request as well
    slowLogThreshold: "10s"

    timeouts:
        # Maximum backend request time for find requests.
        find: "120s"
        # Maximum backend request time for render requests. This is total one and doesn't take into account in-flight requests
        render: "120s"
        # Timeout to connect to the server
        connect: "500ms"

    # Number of concurrent requests to any given backend - default is no limit.
    # If set, you likely want >= MaxIdleConnsPerHost
    concurrencyLimitPerServer: 0

    # Configures how often keep alive packets will be sent out
    keepAliveInterval: "30s"

    # Control http.MaxIdleConnsPerHost. Large values can lead to more idle
    # connections on the backend servers which may bump into limits; tune with care.
    maxIdleConnsPerHost: 100

    # Only affects cases with maxBatchSize > 0. If set to `false` requests after split will be sent out one by one, otherwise in parallel
    doMultipleRequestsIfSplit: false

    # "http://host:port" array of instances of carbonserver stores
    # It MUST be specified.
    backends:

    #backends section will override this one!
    backendsv2:
        backends:
          -
            groupName: "group1"
            # supported:
            #    carbonapi_v2_pb - carbonapi 0.11 or earlier version of protocol.
            #    carbonapi_v3_pb - new protocol, http interface (native)
            #    carbonapi_v3_grpc - new protocol, gRPC interface (native)
            #    protobuf, pb, pb3 - same as carbonapi_v2_pb
            #    msgpack - protocol used by graphite-web 1.1 and metrictank
            #    auto - carbonapi will do it's best to guess if it's carbonapi_v3_pb or carbonapi_v2_pb
            #
            #  non-native protocols will be internally converted to new protocol, which will increase memory consumption
            protocol: "carbonapi_v3_pb"
            # supported:
            #    "broadcast" - send request to all backends in group and merge responses. This was default behavior for carbonapi 0.11 or earlier
            #    "roundrobin" - send request to one backend.
            #    "all - same as "broadcast"
            #    "rr" - same as "roundrobin"
            lbMethod: "broadcast"
            # amount of retries in case of unsuccessful request
            maxTries: 3
            # amount of metrics per fetch request. Default: 0 - unlimited. If not specified, global will be used
            maxBatchSize: 0
            # interval for keep-alive http packets. If not specified, global will be used
            keepAliveInterval: "10s"
            # override for global concurrencyLimit.
            concurrencyLimit: 0
            # override for global maxIdleConnsPerHost
            maxIdleConnsPerHost: 1000
            # force attempt to establish HTTP2 connection, instead of http1.1. Default: false
            # Backends must use https for this to take any effect
            forceAttemptHTTP2: false
            # Only affects cases with maxBatchSize > 0. If set to `false` requests after split will be sent out one by one, otherwise in parallel
            doMultipleRequestsIfSplit: false
            # per-group timeout override. If not specified, global will be used.
            # Please note that ONLY min(global, local) will be used.
            timeouts:
                # Maximum backend request time for find requests.
                find: "300s"
                # Maximum backend request time for render requests. This is total one and doesn't take into account in-flight requests.
                render: "120s"
                # Timeout to connect to the server
                connect: "500ms"
            servers:
                - "http://127.0.0.1:8080"



    # carbonsearch is not used if empty
    carbonsearch:
        # Instance of carbonsearch backend
        # carbonsearch prefix to reserve/register
        # carbonsearch is not used if empty
    # carbonsearch section will override this one!
    carbonsearchv2:
        # Carbonsearch instances. Follows the same syntax as backendsv2
        backends:
            -
              groupName: "group1"
              protocol: "carbonapi_v3_pb"
              lbMethod: "broadcast"
              servers:
                  - "http://127.0.0.1:8080"
        # carbonsearch prefix to reserve/register
        prefix: "virt.v1.*"

    # Enable compatibility with graphite-web 0.9
    # This will affect graphite-web 1.0+ with multiple cluster_servers
    # Default: disabled
    graphite09compat: false


graphTemplates: /etc/go-carbon/graphTemplates.yaml
expireDelaySec: 10
logger:
    - logger: ""
      file: "stderr"
      level: "debug"
      encoding: "console"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
    - logger: ""
      file: "/var/log/go-carbon/carbonapi.log"
      level: "info"
      encoding: "json"
```
